version: "3.3"
services:
  php_apache:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php8_0_2_apache
    depends_on: 
      - mysql
    ports:
      - 8000:80
    volumes:
      - ./docker/php:/var/www/html/
  mysql:
    container_name: mysql_
    image: mysql
    command: "--innodb_use_native_aio=0"
    volumes:
      - "./db_data:/var/lib/mysql"
      - "./mysqlconf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker_database
    ports:
      - "3306:3306"